var FullData = [
    {
        id: 1,
        name: "Nike",
        imageSource: require("../../assets/Fashion/nike1.jpeg"),
        imageSource1: require("../../assets/Fashion/nike2.jpeg"),
        imageSource2: require("../../assets/Fashion/nike3.jpeg"),
        details: "The Nike Revolution 5 ",
        price: "150",
    },
    {
        id: 2,
        name: "ADIDAS",
        imageSource: require("../../assets/Fashion/adidas1.jpeg"),
        imageSource1: require("../../assets/Fashion/adidas2.jpeg"),
        imageSource2: require("../../assets/Fashion/adidas3.jpeg"),
        details: "Solid Men Red T-Shirt",
        price: "100",
    },
    {
        id: 3,
        name: "Levi's",
        imageSource: require("../../assets/Fashion/levis1.jpeg"),
        imageSource1: require("../../assets/Fashion/levis2.jpeg"),
        imageSource2: require("../../assets/Fashion/levis3.jpeg"),
        details: "Slim Men Blue Jeans",
        price: "200",
    },
    {
        id: 4,
        name: "Harpa",
        imageSource: require("../../assets/Fashion/harpa1.jpeg"),
        imageSource1: require("../../assets/Fashion/harpa2.jpeg"),
        imageSource2: require("../../assets/Fashion/harpa3.jpeg"),
        details: "Solid Women Blue Top",
        price: "100",
    },
    {
        id: 5,
        name: "Titan",
        imageSource: require("../../assets/Fashion/titan1.jpeg"),
        imageSource1: require("../../assets/Fashion/titan2.jpeg"),
        imageSource2: require("../../assets/Fashion/titan3.jpeg"),
        details: "Karishma Analog Watch - For Men",
        price: "150",
    },
    {
        id: 6,
        name: "Ensure",
        imageSource: require("../../assets/HealthFitness/ensure1.jpeg"),
        imageSource1: require("../../assets/HealthFitness/ensure2.jpeg"),
        imageSource2: require("../../assets/HealthFitness/ensure3.jpeg"),
        details: "Vanilla Delight Nutrition Drink",
        price: "20",
    },
    {
        id: 7,
        name: "Gym Mat",
        imageSource: require("../../assets/HealthFitness/mat1.jpeg"),
        imageSource1: require("../../assets/HealthFitness/mat2.jpeg"),
        imageSource2: require("../../assets/HealthFitness/mat3.jpeg"),
        details: "Exercise Gym mats For Men & Women ",
        price: "25",
    },
    {
        id:  8,
        name: "KRX Dumbbels",
        imageSource: require("../../assets/HealthFitness/dumbbel1.jpeg"),
        imageSource1: require("../../assets/HealthFitness/dumbbel2.jpeg"),
        imageSource2: require("../../assets/HealthFitness/dumbbel3.jpeg"),
        details: "Adjustable Dumbbell (8 kg)",
        price: "30",
    },
    {
        id:  9,
        name: "NIVIA Gym gloves",
        imageSource: require("../../assets/HealthFitness/glove1.jpeg"),
        imageSource1: require("../../assets/HealthFitness/glove2.jpeg"),
        imageSource2: require("../../assets/HealthFitness/glove3.jpeg"),
        details: "Wrist Band Gym & Fitness Gloves",
        price: "7",
    },
    {
        id:  10,
        name: "MuscleBlaze",
        imageSource: require("../../assets/HealthFitness/whey1.jpeg"),
        imageSource1: require("../../assets/HealthFitness/whey2.jpeg"),
        imageSource2: require("../../assets/HealthFitness/whey3.jpeg"),
        details: "Whey Energy DigeZyme Whey Protein",
        price: "50",
    },
    {
        id: 11,
        name: "Lizol",
        imageSource: require("../../assets/Essentials/lizol1.jpeg"),
        imageSource1: require("../../assets/Essentials/lizol2.jpeg"),
        imageSource2: require("../../assets/Essentials/lizol3.jpeg"),
        details: "Disinfectant Surface Cleaner Citrus",
        price: "3",
    },
    {
        id:  12,
        name: "Rostaa Almond",
        imageSource: require("../../assets/Essentials/almond1.jpeg"),
        imageSource1: require("../../assets/Essentials/almond2.jpeg"),
        imageSource2: require("../../assets/Essentials/almond3.jpeg"),
        details: "Classic almonds crunchy",
        price: "10",
    },
    {
        id:  13,
        name: "Nestle Milkmaid",
        imageSource: require("../../assets/Essentials/mm1.jpeg"),
        imageSource1: require("../../assets/Essentials/mm2.jpeg"),
        imageSource2: require("../../assets/Essentials/mm3.jpeg"),
        details: "Eatables",
        price: "3",
    },
    {
        id: 14,
        name: "Tata Filter Coffee",
        imageSource: require("../../assets/Essentials/coffee1.jpeg"),
        imageSource1: require("../../assets/Essentials/coffee2.jpeg"),
        imageSource2: require("../../assets/Essentials/coffee3.jpeg"),
        details: "Flavoured coffee beans",
        price: "10",
    },
    {
        id: 15,
        name: "Kellogg's",
        imageSource: require("../../assets/Essentials/flakes1.jpeg"),
        imageSource1: require("../../assets/Essentials/flakes2.jpeg"),
        imageSource2: require("../../assets/Essentials/flakes3.jpeg"),
        details: "Corn flakes with real almond",
        price: "12",
    },  
  ];
  module.exports = FullData;
  